cc_binary(
    name = "pure_attribute",
    srcs = [ "pure_attribute.cpp", ],
)

cc_binary(
    name = "constexpr_fun",
    srcs = [ "constexpr_fun.cpp", ],
    deps = [
        "//third_party:fmt"
    ]
)
